### PR TITLE
interpolate freqs

### PR DESCRIPTION
**Pull request by parasharmohapatra**
I think you should be able to understand the changes pretty easily

### CODE REVIEW

**Review by raphaelcervantes — COMMENTED** [review]
@parashar2399 Can you upload the filename?

**Comment by parasharmohapatra** [comment]
@raphaelcervantes I can't? I don't know the file name that you use for your data.

**Comment by raphaelcervantes** [comment]
@parashar2399 Don't you have one for dielectrics? Can you use the one for the points you measured?

**Comment by parasharmohapatra** [comment]
@raphaelcervantes yeah I shall do that then. I thought you had data from new simulations. The ones I create for dielectric measurement won't work in ln2 though

**Comment by raphaelcervantes** [comment]
@parashar2399 That's fine. I can make a new file for liquid nitrogen.

**Comment by parasharmohapatra** [comment]
@raphaelcervantes I have uploaded a txt file with prediction of dielectric data. 
if you set` narrow_scan = False`, then the np.loadtxt will be ignored.

**Review by raphaelcervantes — APPROVED** [review]

**Comment by parashar2399** [comment]
@raphaelcervantes I don’t really understand the need for cubic interpolation unless the linear interpolation using numpy wasn’t good enough. I also don’t see a huge advantage of having slightly better interpolation give than we have a narrow scan span of 400e6 Hz. Other than that it looks fine.

**Review by parasharmohapatra — COMMENTED** [review]
@raphaelcervantes  I don’t really understand the need for cubic interpolation unless the linear interpolation using numpy wasn’t good enough. I also don’t see a huge advantage of having slightly better interpolation give than we have a narrow scan span of 400e6 Hz. Other than that it looks fine.

**Comment by raphaelcervantes** [comment]
@parashar2399 I was desperate at one point to see the mode. It turns out that we were in the wrong frequency span. For whatever reason, but mode appeared at a different place at higher frequencies. I'm trying to understand why.

I think it will be easier to build on top of the scipy function.

**Comment by raphaelcervantes** [comment]
@parashar2399 can you look over my list of changes. I would like to merge this branch to master as soon as I can to avoid further merge conflicts

**Review by parasharmohapatra — COMMENTED** [review]
@raphaelcervantes 
for log_vna_data/log_modemap (they are the same thing) I do not see a parameter for autoscale. But, autoscale is something that is being checked for in the function
line 48 and 57 in data_logging.py

**Comment by raphaelcervantes** [comment]
@parashar2399 that was a good catch. What about now?

**Review by parasharmohapatra — COMMENTED** [review]
Looks good now

**Pull request merged**
