### PR TITLE
added predictions for empty resonator

### PR DESCRIPTION
**Pull request by raphaelcervantes**
I just added some configuration changes. Added file for empty modemap measurement.

### CODE REVIEW

**Comment by parasharmohapatra** [comment]
@raphaelcervantes Don't you think it might be better practice to just adding a new variable to all the configs? I haven't tested this out but, it might work well for one config but not for the other.

**Comment by raphaelcervantes** [comment]
@parashar2399 I don't understand what you mean.

**Comment by parasharmohapatra** [comment]
@raphaelcervantes So the dielectric_modemap config has predicted frequency file. But, the empty resonator, ln2_empty configs dont have a predicted resonances file. I think we should just consistently have a variable for those and set it equal to None

**Comment by raphaelcervantes** [comment]
I agree. I thought I had defined a data file for the ln2 dielectric. I must have done it inside of a container and forgot to propogate those changes to the git repository. I will fix this.

**Comment by raphaelcervantes** [comment]
@parashar2399 can you review the pull request now?

**Review by parasharmohapatra — CHANGES_REQUESTED** [review]
@raphaelcervantes the narrowscan won't work for ln2 measurements because the ifile_predicted_resonances parameter is missing from the configs. If that is ok with you then I can merge this otherwise, I can add it.

**Comment by raphaelcervantes** [comment]
Either solution is fine for now. I don't expect to do an LN2 measurement anytime soon.

**Review by parasharmohapatra — APPROVED** [review]

**Pull request merged**
